name: GitHub Actions Example

on: [push]
    pull_request:
    branches: [ main ]

jobs: launcher
build:
    name: Test
    runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
    node-version: 16.x
    run: npm ci
    run: npm test